config/routes.rb
Rails.application.routes.draw do
  devise_for :companies, controllers: {
    sessions: 'companies/sessions',
    passwords: 'companies/passwords',
    registrations: 'companies/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/products/download/:id' => 'products#download', as: "download_drawing"
  resources :companies, only: [:index, :show, :edit, :update]
  resources :products do
    get :search, on: :collection
    resources :estimates, only: [:new, :create]
  end
  resources :estimates, only: [:index, :show, :update]

end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :estimates

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_num, presence: true
end

app/controllers/companies/confirmations_controller.rb
# frozen_string_literal: true

class Companies::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/companies/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Companies::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/companies/passwords_controller.rb
# frozen_string_literal: true

class Companies::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/companies/registrations_controller.rb
# frozen_string_literal: true

class Companies::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :name_kana, :postal_code, :address, :phone_num, :fax_num])
  end

end

app/controllers/companies/sessions_controller.rb
# frozen_string_literal: true

class Companies::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/companies/unlocks_controller.rb
# frozen_string_literal: true

class Companies::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_company!, only: [:edit, :update]

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
    @products = @company.products
    @types = Type.all
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      flash[:notice] = "情報を更新しました"
      redirect_to company_path(@company.id)
    else
      render :edit
    end
  end

  private

  def company_params
    params.require(:company).permit(
      :name,
      :name_kana,
      :postal_code,
      :address,
      :phone_num,
      :fax_num,
      :description
      )
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/edit.html.erb
<div id="pagetitle" class="edit-company-title">
  <h1>
    Edit Company Info
    <span>企業情報編集</span>
  </h1>
</div>

<div class="container">
  <% if @company.errors.any? %>
    <%= @company.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <%= form_with model: @company, local: true do |f| %>
    <div class="form-group col-md-5">
      <%= f.label :name, "企業名", class: "form-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group col-md-5">
      <%= f.label :name_kana, "企業名(カナ)", class: "form-label" %>
      <%= f.text_field :name_kana, class: "form-control" %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :postal_code, "郵便番号", class: "form-label" %>
      <%= f.text_field :postal_code, class: "form-control" %>
    </div>
    <div class="form-group col-md-5">
      <%= f.label :address, "所在地", class: "form-label" %>
      <%= f.text_field :address, class: "form-control" %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :phone_num, "電話番号", class: "form-label" %>
      <%= f.text_field :phone_num, class: "form-control" %>
    </div>
    <div class="form-group col-md-4">
      <%= f.label :fax_num, "FAX", class: "form-label" %>
      <%= f.text_field :fax_num, class: "form-control" %>
    </div>
    <div class="form-group col-auto">
      <%= f.label :description, "企業概要", class: "form-label" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group col-auto">
      <%= f.submit "更新", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/companies/index.html.erb
<div id="pagetitle" class="companies-title">
  <h1>
    Companies
    <span>メーカー一覧</span>
  </h1>
</div>

<div class="container">
  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>企業名</th>
        <th>所在地</th>
        <th>電話番号</th>
      </tr>
    </thead>
    <tbody>
      <% @companies.each do |company| %>
        <tr>
          <td>
            <%= link_to company.name, company_path(company.id) %>
          </td>
          <td>
            <%= "〒#{company.postal_code}" %><br>
            <%= company.address %>
          </td>
          <td>
            <%= company.phone_num %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/companies/show.html.erb
<div id="pagetitle" class="company-title">
  <h1>
    Company
    <span>企業情報</span>
  </h1>
</div>

<div class="container">
  <h2 class="main-title"><%= @company.name %></h2>
  <div class="content-container">
    <h3 class="content-title">企業概要</h3>
    <p><%= @company.description %></p>
  </div>
  <div class="content-container">
    <h3 class="content-title">企業情報</h3>
    <table class="table align-middle">
      <tr>
        <th>会社所在地</th>
        <td>
          <%= "〒#{@company.postal_code}" %><br>
          <%= @company.address %>
        </td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @company.phone_num %></td>
      </tr>
      <% if @company.fax_num != nil %>
        <tr>
          <th>FAX</th>
          <td><%= @company.fax_num %></td>
        </tr>
      <% end %>
      <% if @company == current_company %>
        <tr>
          <td colspan="2">
            <%= link_to "編集", edit_company_path(@company.id), class: "btn btn-secondary" %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="content-container">
    <h3 class="content-title">製品一覧</h3>
    <div class="container">
      <%= render 'products/list', products: @products, types: @types %>
    </div>
  </div>
</div>