config/routes.rb
Rails.application.routes.draw do
  devise_for :companies, controllers: {
    sessions: 'companies/sessions',
    passwords: 'companies/passwords',
    registrations: 'companies/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/products/download/:id' => 'products#download', as: "download_drawing"
  resources :companies, only: [:index, :show, :edit, :update]
  resources :products do
    get :search, on: :collection
    resources :estimates, only: [:new, :create]
  end
  resources :estimates, only: [:index, :show, :update]

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
  has_many :product_images, dependent: :destroy
  belongs_to :type
  has_many :estimates, dependent: :destroy
  has_many :sizes, dependent: :destroy

  validates :company_id, presence: true
  validates :type_id, presence: true
  validates :name, presence: true
  validates :description, presence: true

  accepts_nested_attributes_for :sizes, allow_destroy: true
  accepts_attachments_for :product_images, attachment: :image
  mount_uploader :drawing, DrawingUploader
end

app/controllers/maker/products_controller.rb
class Maker::ProductsController < ApplicationController
  def new
    @product = Product.new
    @product.product_images.new
  end

  def create
    @product = Product.new(product_params)
    @product.company_id = current_company.id
    #製品タイプモデル作成後修正
    @product.type_id = 0
    if @product.save
      flash[:notice] = "製品の登録が完了しました"
      redirect_to maker_products_path
    else
      render :new
    end
  end

  def index
    @products = Product.where(company_id: current_company.id)
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def product_params
    params.require(:product).permit(:type_id, :name, :description, product_images_images: [])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_company!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @product = Product.new
    @product.sizes.build
    @product.product_images.new
  end

  def create
    @product = Product.new(product_params)
    @product.company_id = current_company.id
    if @product.save
      flash[:notice] = "製品の登録が完了しました"
      redirect_to company_path(current_company.id)
    else
      render :new
    end
  end

  def index
    @products = Product.all
    @types = Type.all
  end

  def show
    @product = Product.find(params[:id])
    @sizes = @product.sizes
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "製品情報を更新しました"
      redirect_to product_path(@product.id)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "製品を削除しました"
    redirect_to company_path(current_company.id)
  end

  def download
    @product = Product.find(params[:id])
    send_data(@product.drawing.read, filename: @product.drawing_identifier)
  end

  def search
    if params[:word].present?
      @products = Product.where('name LIKE ?', "%#{params[:word]}%")
    else
      @products = Product.none
    end
  end

  private

  def product_params
    params.require(:product).permit(
      :type_id,
      :name,
      :description,
      :drawing,
      sizes_attributes: [
        :id,
        :product_id,
        :name,
        :_destroy
        ],
      product_images_images: []
      )
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_list.html.erb
<div id="search-container">
  <%= form_with url: search_products_path, method: :get, local: true do |f| %>
    <div class="form-row align-items-center">
      <div class="title">
        <p>
          Search
          <span>製品検索</span>
        </p>
      </div>
      <div class="col-md-6 ml-auto">
       <%= f.text_field :word, class: "form-control" %>
      </div>
      <div class="col-auto mr-auto">
       <%= f.submit "検索", class: "btn btn-secondary" %>
      </div>
    </div>
  <% end %>
</div>
<ul id="type-menu">
  <% types.each_with_index do |type, i| %>
    <li><%= link_to type.name, "#type#{i}" %></li>
    <div id="<%= "type#{i}" %>" class="type-content">
      <% if products.where(type_id: type.id).any? %>
        <% products.where(type_id: type.id).each do |product| %>
          <div class="product-container">
            <%= link_to product_path(product.id) do %>
              <%= attachment_image_tag product.product_images.first, :image, format: 'jpeg', fallback: "no_img.jpeg", class: "container-image" %>
              <span class="container-title">
                <%= product.name %>
              </span>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <p>製品がありません</p>
      <% end %>
    </div>
  <% end %>
</ul>

app/views/products/_size_fields.html.erb
<div class="nested-fields mb-2">
  <div class="row">
    <div class="col-auto">
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="col-auto">
      <%= link_to_remove_association "寸法を削除", f, class: "btn btn-danger" %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div id="pagetitle" class="edit-product-title">
  <h1>
    Edit Product Info
    <span>製品情報編集</span>
  </h1>
</div>

<div class="container">
  <% if @product.errors.any? %>
    <% @products.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <%= form_with model: @product, local: true do |f| %>
    <div class="form-group">
      <%= f.label :name, "製品名", class: "form-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :type_id, "製品タイプ", class: "form-label" %>
      <%= f.collection_select :type_id, Type.all, :id, :name, {include_blank: "選択してください"}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :description, "製品概要", class: "form-label" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :product_images_images, "製品画像", class: "form-label" %>
      <%= f.attachment_field :product_images_images, multiple: true, class: "form-control-file" %>
    </div>
    <div class="form-group">
      <%= f.fields_for :sizes do |builder| %>
        <%= f.label :name, "呼び寸法 / 品名", class: "form-label" %>
        <%= render 'size_fields', f: builder %>
        <div id="detail-association-insertion-point"></div>
        <%= link_to_add_association "寸法を追加", f, :sizes, class: "btn btn-primary",
          data: {
            association_insertion_node: '#detail-association-insertion-point',
            association_insertion_method: 'append'
          }
        %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :drawing, "図面データ", class: "form-label" %>
      <%= f.file_field :drawing, class: "form-control-file" %>
    </div>
    <div class="form-group">
      <%= f.submit "更新", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/products/index.html.erb
<div id="pagetitle" class="products-title">
  <h1>
    Products
    <span>製品一覧</span>
  </h1>
</div>

<div class="container">
 <%= render 'products/list', products: @products, types: @types %>
</div>

app/views/products/new.html.erb
<div id="pagetitle" class="new-product-title">
  <h1>
    New Product
    <span>新規製品登録</span>
  </h1>
</div>

<div class="container">
  <% if @product.errors.any? %>
    <% @product.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <%= form_with model: @product, local: true do |f| %>
    <div class="form-group">
      <%= f.label :name, "製品名", class: "form-label" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :type_id, "製品タイプ", class: "form-label" %>
      <%= f.collection_select :type_id, Type.all, :id, :name, {include_blank: "選択してください"}, {class: "form-control"} %>
    </div>
    <div class="form-group">
      <%= f.label :description, "製品概要", class: "form-label" %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :product_images_images, "製品画像", class: "form-label" %>
      <%= f.attachment_field :product_images_images, multiple: true, class: "form-control-file" %>
    </div>
    <div class="form-group">
      <%= f.fields_for :sizes do |builder| %>
        <%= f.label :name, "呼び寸法 / 品名", class: "form-label" %>
        <%= render 'size_fields', f: builder %>
        <div id="detail-association-insertion-point"></div>
        <%= link_to_add_association "寸法を追加", f, :sizes, class: "btn btn-primary",
          data: {
            association_insertion_node: '#detail-association-insertion-point',
            association_insertion_method: 'append'
          }
        %>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :drawing, "図面データ", class: "form-label" %>
      <%= f.file_field :drawing, class: "form-control-file" %>
    </div>
    <div class="form-group">
      <%= f.submit "登録", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/products/search.html.erb
<div id="pagetitle" class="products-title">
  <h1>
    Products
    <span>製品一覧</span>
  </h1>
</div>

<div class="container">
  <div id="search-container">
    <%= form_with url: search_products_path, method: :get, local: true do |f| %>
      <div class="form-row align-items-center">
        <div class="title">
          <p>
            Search
            <span>製品検索</span>
          </p>
        </div>
        <div class="col-md-6 ml-auto">
         <%= f.text_field :word, class: "form-control" %>
        </div>
        <div class="col-auto mr-auto">
         <%= f.submit "検索", class: "btn btn-secondary" %>
        </div>
      </div>
    <% end %>
  </div>

  <div class="search-result mt-3">
    <% if @products.any? %>
      <% @products.each do |product| %>
        <div class="product-container">
          <%= link_to product_path(product.id) do %>
            <%= attachment_image_tag product.product_images.first, :image, format: 'jpeg', fallback: "no_img.jpeg", class: "container-image" %>
            <span class="container-title">
              <%= product.name %>
            </span>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <p>製品がありません</p>
    <% end %>
  </div>

</div>

app/views/products/show.html.erb
<div id="product-show" class="container">
  <h1 class="main-title"><%= @product.name %></h1>
  <div class="product-image-container">
    <div id="slider">
      <% @product.product_images.each do |image| %>
        <%= attachment_image_tag image, :image, format: 'jpeg', class: "product-image" %>
      <% end %>
    </div>
  </div>
  <div class="content-container">
    <h2 class="content-title">製品概要</h2>
    <%= @product.description %>
  </div>
  <div class="content-container">
    <h2 class="content-title">製品寸法</h2>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>
            呼び寸法 / 品名
          </th>
        </tr>
      </thead>
      <tbody>
        <% @sizes.each do |size| %>
          <tr>
            <td>
              <%= size.name %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="content-container">
    <h2 class="content-title">Download</h2>
    <%= link_to "図面ダウンロード", download_drawing_path(@product.id) %>
  </div>
  <% if @product.company == current_company %>
    <div class="content-container">
      <h2 class="content-title">管理者機能</h2>
      <%= link_to "編集", edit_product_path(@product.id), class: "btn btn-secondary" %>
      <%= link_to "削除", product_path(@product.id), method: :delete, data: {confirm: "削除しますか？"}, class: "btn btn-danger" %>
    </div>
  <% end %>
  <% if user_signed_in? %>
    <div class="content-container">
      <h2 class="content-title">見積依頼</h2>
      <%= link_to "見積依頼を作成", new_product_estimate_path(@product.id) %>
    </div>
  <% end %>
</div>