config/routes.rb
Rails.application.routes.draw do
  devise_for :companies, controllers: {
    sessions: 'companies/sessions',
    passwords: 'companies/passwords',
    registrations: 'companies/registrations'
  }
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  root to: 'homes#top'
  get '/about' => 'homes#about'
  get '/products/download/:id' => 'products#download', as: "download_drawing"
  resources :companies, only: [:index, :show, :edit, :update]
  resources :products do
    get :search, on: :collection
    resources :estimates, only: [:new, :create]
  end
  resources :estimates, only: [:index, :show, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :estimates

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_num, presence: true
end

app/models/estimate.rb
class Estimate < ApplicationRecord
  belongs_to :user
  belongs_to :company
  belongs_to :product

  validates :user_id, presence: true
  validates :company_id, presence: true
  validates :product_id, presence: true
  validates :description, presence: true
  validates :status, presence: true

  enum status: [:"受付中", :"送付済"]
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
  has_many :product_images, dependent: :destroy
  belongs_to :type
  has_many :estimates, dependent: :destroy
  has_many :sizes, dependent: :destroy

  validates :company_id, presence: true
  validates :type_id, presence: true
  validates :name, presence: true
  validates :description, presence: true

  accepts_nested_attributes_for :sizes, allow_destroy: true
  accepts_attachments_for :product_images, attachment: :image
  mount_uploader :drawing, DrawingUploader
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
  belongs_to :product
  attachment :image
end

app/models/size.rb
class Size < ApplicationRecord
  belongs_to :product
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :estimates, dependent: :destroy

  validates :name, presence: true
  validates :group, presence: true
  validates :department, presence: true
  validates :phone_num, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def authenticate_any!
    if user_signed_in?
      true
    else
      authenticate_company!
    end
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_company!, only: [:edit, :update]

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
    @products = @company.products
    @types = Type.all
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update(company_params)
      flash[:notice] = "情報を更新しました"
      redirect_to company_path(@company.id)
    else
      render :edit
    end
  end

  private

  def company_params
    params.require(:company).permit(
      :name,
      :name_kana,
      :postal_code,
      :address,
      :phone_num,
      :fax_num,
      :description
      )
  end

end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  before_action :authenticate_company!, only: [:update]
  before_action :authenticate_any!, only: [:index, :show]

  def new
    @estimate = Estimate.new
    @product = Product.find(params[:product_id])
  end

  def create
    @estimate = Estimate.new(estimate_params)
    @estimate.user_id = current_user.id
    product = Product.find(params[:product_id])
    @estimate.company_id = product.company.id
    @estimate.product_id = product.id
    if @estimate.save
      flash[:notice] = "見積依頼を送信しました"
      redirect_to estimates_path
    else
      render :new
    end
  end

  def index
    if user_signed_in?
      @estimates = current_user.estimates
    elsif company_signed_in?
      @estimates = current_company.estimates
    end
  end

  def show
    @estimate = Estimate.find(params[:id])
  end

  def update
    @estimate = Estimate.find(params[:id])
    if @estimate.update(estimate_params)
      flash[:notice] = "ステータスを更新しました"
      redirect_to estimate_path(@estimate.id)
    else
      render :show
    end
  end

  private

  def estimate_params
    params.require(:estimate).permit(
      :description,
      :status
      )
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/maker/products_controller.rb
class Maker::ProductsController < ApplicationController
  def new
    @product = Product.new
    @product.product_images.new
  end

  def create
    @product = Product.new(product_params)
    @product.company_id = current_company.id
    #製品タイプモデル作成後修正
    @product.type_id = 0
    if @product.save
      flash[:notice] = "製品の登録が完了しました"
      redirect_to maker_products_path
    else
      render :new
    end
  end

  def index
    @products = Product.where(company_id: current_company.id)
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def product_params
    params.require(:product).permit(:type_id, :name, :description, product_images_images: [])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_company!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @product = Product.new
    @product.sizes.build
    @product.product_images.new
  end

  def create
    @product = Product.new(product_params)
    @product.company_id = current_company.id
    if @product.save
      flash[:notice] = "製品の登録が完了しました"
      redirect_to company_path(current_company.id)
    else
      render :new
    end
  end

  def index
    @products = Product.all
    @types = Type.all
  end

  def show
    @product = Product.find(params[:id])
    @sizes = @product.sizes
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "製品情報を更新しました"
      redirect_to product_path(@product.id)
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = "製品を削除しました"
    redirect_to company_path(current_company.id)
  end

  def download
    @product = Product.find(params[:id])
    send_data(@product.drawing.read, filename: @product.drawing_identifier)
  end

  def search
    if params[:word].present?
      @products = Product.where('name LIKE ?', "%#{params[:word]}%")
    else
      @products = Product.none
    end
  end

  private

  def product_params
    params.require(:product).permit(
      :type_id,
      :name,
      :description,
      :drawing,
      sizes_attributes: [
        :id,
        :product_id,
        :name,
        :_destroy
        ],
      product_images_images: []
      )
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CIVCON</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <%= link_to "CIVCON", root_path, class: "navbar-brand" %>
          <% if user_signed_in? %>
            <%= "ようこそ#{current_user.name}さん" %>
          <% elsif company_signed_in? %>
            <%= "#{current_company.name}としてログインしています" %>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <%= link_to "About", about_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "製品一覧", products_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "メーカー一覧", companies_path, class: "nav-link" %>
              </li>
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "見積依頼一覧", estimates_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
                </li>
              <% elsif company_signed_in? %>
                <li class="nav-item">
                  <%= link_to "見積依頼一覧", estimates_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "製品登録", new_product_path, class: "nav-link" %>
                </li>
                <li class="nav-iten">
                  <%= link_to "自社ページ", company_path(current_company.id), class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_company_session_path, method: :delete, class: "nav-link" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>

    <%= yield %>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">© CIVCON</p>
      </div>
    </footer>
  </body>
</html>